### ISSUE TITLE
Installation guide needs rework

### ISSUE THREAD

**Issue by mwinkens** [clarin-eric/B2Drop2LRSwitchboard#11]
Step 2 and 3 in your installation guide are not up to date/contain mistakes:

```markdown
   2. git clone https://github.com/clarin-eric/B2Drop2LRSwitchboard.git lrswitchboardbridge 
   3. in the apps folder, execute: mv B2Drop2LRSwitchboard switchboardBridge
```
I suggest cancelling step 3 and directly installing the app into `switchboardBridge`. Also step 3 currently tries to move a directory `B2Drop2LRSwichtboard` which doesn't exist.

Also you may want to add the enable-command as alternative to activate the app:
`php occ app:enable switchboardBridge`

**Comment by claus-zinn** [comment]
done.
