### ISSUE TITLE
Automatic sharing link creation

### ISSUE THREAD

**Issue by hashmich** [clarin-eric/B2Drop2LRSwitchboard#3]
Automatically create the public sharing link, when file sharing to the LRS is requested. 

Currently, the sharing link has to be created manually, before the file can be shared over to the LRS. A warning pops up, when it is not present.

**Comment by hashmich** [comment]
A working test version is available in feature branch. 

Problems faced on the way:
in existing code, we get /ocs/v1.php from OC.linkToOCS(path, integer(?)).
As of https://docs.nextcloud.com/server/15/developer_manual/core/ocs-share-api.html,
sharing API should be accessed via /ocs/v2.php:
    http://localhost:8088/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json
No idea where to find documentation about OC.linkToOCS - what about second param???
Error message points to 
    http://www.freedesktop.org/wiki/Specifications/open-collaboration-services
but no useful hints

//var url = OC.linkToOCS('apps/files_sharing/api/v1/shares?format=json', 4);  // works, returns error
//var url = OC.generateUrl('apps/files_sharing/api/v1/shares?format=json');  // does not work

URL called from the NC-15 UI add-link button:
// var url = http://localhost:8088/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json';  // works

Now using following construction:
    var url = '/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json';

**Comment by andmor-** [comment]
Closed by a49e835
