### ISSUE TITLE
Nextcloud 16 support

### ISSUE THREAD

**Issue by apw1388** [clarin-eric/B2Drop2LRSwitchboard#5]
Please prepare the app for Nextcloud 16.

**Comment by apw1388** [comment]
The app should work indipendend from B2SHAREbridge. On out development server everything is fine with the B2SHAREbridge on master branch. If you tried old versions of the B2SHAREbridge with latest Nextcloud versions, there will be some issues.

**Comment by andmor-** [comment]
I just updated the max NC version to 16 and tried it in [our NC 16.0.5 test instance](https://nextcloud.clarin-dev.eu).
As much as I can tell, it all works as usual and I can see the context menu.
@hashmich can you do some further testing?

![Screen Shot 2019-11-11 at 13 48 19](https://user-images.githubusercontent.com/6597509/68589037-325ad400-048b-11ea-9c70-60ee103199a2.png)

**Comment by hashmich** [comment]
Sorry I don't have capacity to do more tests/investigations what went wrong before end of November until final release of the new DHCR-frontend. 
But I'm happy to hear that andmore's test went well, however. 
I was using NC 16.0.1.1 (Docker wonderfall/nextcloud:16) and latest version of B2DROPLRS with max-version manually patched. Yet not clear to me, how B2DROPLRS and B2ShareBridge should be kept in sync or how/where they've been branched.

**Comment by andmor-** [comment]
I mean, can you go to https://nextcloud.clarin-dev.eu/ and check if the functionalities you are familiar with are working as you remember them?
This is to make sure that the plugin is working when B2Drop is updated to NC 16

**Comment by hashmich** [comment]
This was fairly simple!
I was overcomplicate-thinking ;-)
So far everything is as it should, auto-creation of sharing link still works.

**Comment by claus-zinn** [comment]
Issue has long been resolved. Closing it.
