### ISSUE TITLE
Update app bootstrapping

### ISSUE THREAD

**Issue by apw1388** [clarin-eric/B2Drop2LRSwitchboard#9]
Since Nextcloud 20 the app bootstrapping has changed. The appinfo/app.php became deprecated. Further information can be found here [1]. The deprecated app.php floods the NExtcloud log. Please update the bootstrapping of your app.

[1]: https://docs.nextcloud.com/server/21/developer_manual/app_development/bootstrap.html#nextcloud-20-and-later

**Comment by claus-zinn** [comment]
Has been resolved with summer'22 version of the bridge. Closing the issue
